# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrecord', models.IntegerField()),
                ('meeting', models.TextField()),
                ('date1', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('date', models.DateTimeField()),
                ('pic_url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Userdata'),
        ),
    ]
