# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='pic_url',
            field=models.CharField(max_length=250),
        ),
    ]
